
apiVersion: apps/v1
kind: Deployment #ReplicaSet
metadata:
  name: webapp
spec:
  #minReadySeconds: 30 #Default is 0 and it was used just for the testing purpose
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:  #template for the pod
    metadata:
      labels: #used to be mapped with service and hence can be used and exposed to outside world
        app: webapp #used in the service
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels: #used to be mapped with service and hence can be used and exposed to outside world
    app: queue
    release: "1"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
